 <header>
   	<div class="logo">
   		<div>
   			<img src="https://img.icons8.com/cotton/64/000000/online-order.png">
   		</div>
   		<div>
   			<h1>Store test</h1>
            <h2>Sistema de pedido produtos</h2>
   		</div>
   	</div>
      <nav>
         <ul>
            <li><a href="<?=base_url('/')?>">Clientes</a></li>
            <li><a href="<?=base_url('/produtos')?>">Produtos</a></li>
            <li><a href="<?=base_url('/pedidos')?>">Pedidos</a></li>
         </ul>
      </nav>
</header>